---
- hosts: localhost
  tasks:

  - name: Pull the tomcat container image
    docker_image:
      name: tomcat:latest
      source: pull

  - name: Build image with buils args
    docker_image:
      name: docker-image
      build:
        path: /home/ec2-user
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Run the container
    cmd: docker run -dit -p 8080:8080 --name docker-container docker-image
